CREATE TABLE IF NOT EXISTS restaurant_hub.tipos_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    tipo VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS restaurant_hub.usuarios_tipos_usuario (
    usuario_id BIGINT NOT NULL,
    tipo_usuario_id BIGINT NOT NULL,
    CONSTRAINT pk_usuarios_tipos_usuario PRIMARY KEY (usuario_id, tipo_usuario_id),
    CONSTRAINT fk_usuarios_tipos_usuario_usuario FOREIGN KEY (usuario_id)
        REFERENCES restaurant_hub.usuarios (id) ON DELETE CASCADE,
    CONSTRAINT fk_usuarios_tipos_usuario_tipo FOREIGN KEY (tipo_usuario_id)
        REFERENCES restaurant_hub.tipos_usuario (id) ON DELETE CASCADE
);
