CREATE TABLE IF NOT EXISTS restaurant_hub.restaurantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    endereco VARCHAR(255) NOT NULL,
    tipo_cozinha VARCHAR(100) NOT NULL,
    horario_funcionamento VARCHAR(100) NOT NULL,
    dono_usuario_id BIGINT NOT NULL,
    CONSTRAINT fk_restaurantes_dono FOREIGN KEY (dono_usuario_id)
        REFERENCES restaurant_hub.usuarios (id)
);
