CREATE TABLE restaurant_hub.itens_cardapio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurante_id BIGINT NOT NULL,
    nome VARCHAR(150) NOT NULL,
    descricao VARCHAR(500) NOT NULL,
    preco DECIMAL(10, 2) NOT NULL,
    apenas_consumo_no_local BOOLEAN NOT NULL,
    caminho_foto VARCHAR(255) NOT NULL,
    CONSTRAINT fk_itens_cardapio_restaurante
        FOREIGN KEY (restaurante_id)
        REFERENCES restaurant_hub.restaurantes (id)
);
